os:
  - linux
  - osx

osx_image: xcode11.4

language: generic

cache: 
  directories:
    - $HOME/cache

before_install:
  - chmod 777 ./script/travis.sh
  - ./script/travis.sh before_install

script:
  chmod 777 ./script/travis.sh
  - ./script/travis.sh script