os:
  - linux
  # - osx

# osx_image: xcode11.4

language: generic

cache: 
  directories:
    - $HOME/cache

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gnat gprbuild

script:
  - gprbuild -j0 -p
